### ISSUE TITLE
Parenthesis parsing broken for decimal numbers

### ISSUE THREAD

**Issue by SBvanAlbada** [spaghettiboys/oppgavegenerator#2]
In exercise 112, parethetis parsing did not work. All parentheses around variables were still there. This exercise includes one floating point variable. When I replaced this floating point variable to an integer variable, parsing worked perfectly again.
<img width="1280" alt="skjermbilde 2015-08-24 kl 11 15 33" src="https://cloud.githubusercontent.com/assets/13903572/9436808/4ba973fa-4a52-11e5-8866-744f1575a62c.png">

**Comment by Enrahim** [comment]
oppgavegenerator / oppgavegen / parsing / parenthesis_removal.py  line 18 splits at '.'
That probably result in this bug. Why was that included in the first place?
