### ISSUE TITLE
"Foprgot password" not working

### ISSUE THREAD

**Issue by strazdinsg** [spaghettiboys/oppgavegenerator#7]
The whole procedure gets until "done" page, but I do not receive any email with password reset instructions.

**Comment by ampled** [comment]
Just tested locally with a gmail smtp setup, and it worked just fine. Does your user have an e-mail address? (when creating an admin user with the createsuperuser-command, it's not required to put in an e-mail address)

![image](https://cloud.githubusercontent.com/assets/6841690/10230769/38245de0-687f-11e5-836b-615d45ddd5e2.png)

**Comment by ampled** [comment]
This should be resolved. However, keep in mind that new e-mail servers usually aren't trusted by the big e-mail providers like gmail. I tested this on the currently deployed server and the received e-mail ended up in the spam-folder.
